// ─────────────────────────────────────────────────
// app.js — Andiamo al cinema?
// Do NOT edit this file to update schedules.
// Edit data.json instead, then push to GitHub.
// ─────────────────────────────────────────────────

var CINEMAS, FILMS, SHOWTIMES;
var cinemaById = {}, filmById = {};
var ALL_RECORDS = [];
var posterCache = {}, ratingCache = {};
var TMDB_KEY = '';

// State — initialised after data.json loads
var S={range:'today', area:'Tutte', genres:new Set(), tab:'film', q:'', ov:false, stasera:false};
var AREA_ORDER=['Centro / Duomo','Brera / Garibaldi','Navigli / Porta Genova',
  'Porta Venezia / Citta Studi','CityLife / Fiera','Ovest / Corsico',
  'Est / Lambrate','Bicocca / Bovisa','Altre zone'];
var ALL_AREAS=['Tutte'].concat(AREA_ORDER);
var ALL_GENRES=[];

var posterCache={}, ratingCache={};
function fetchPoster(filmId, tmdbId){
  if(!TMDB_KEY||!tmdbId||posterCache[filmId]!==undefined) return;
  posterCache[filmId]=null;
  fetch('https://api.themoviedb.org/3/movie/'+tmdbId+'?api_key='+TMDB_KEY+'&language=it-IT')
    .then(function(r){return r.ok?r.json():null;})
    .then(function(d){
      if(!d) return;
      if(d.poster_path) posterCache[filmId]='https://image.tmdb.org/t/p/w342'+d.poster_path;
      if(d.vote_average&&d.vote_count>50) ratingCache[filmId]=Math.round(d.vote_average*10)/10;
      document.querySelectorAll('[data-filmid="'+filmId+'"]').forEach(function(el){
        var pw=el.querySelector('.card-poster');
        if(pw) pw.innerHTML=posterInnerHTML(filmId);
      });
    }).catch(function(){});
}

function posterInnerHTML(filmId){
  var film=filmById[filmId];
  var url=film&&film.poster?film.poster:(posterCache[filmId]||null);
  if(url) return '<img src="'+url+'" alt="" loading="lazy">';
  return '<div class="card-poster-placeholder">'+(film?film.emoji:'🎞')+'</div>';
}

function buildFilters(){
  var areaEmoji={
    'Centro / Duomo':'🏛️',
    'Brera / Garibaldi':'🎨',
    'Navigli / Porta Genova':'🚤',
    'Porta Venezia / Citta Studi':'📚',
    'CityLife / Fiera':'🏙️',
    'Ovest / Corsico':'🌿',
    'Est / Lambrate':'🏭',
    'Bicocca / Bovisa':'🔬',
    'Altre zone':'📍'
  };
  var aHtml=ALL_AREAS.map(function(a){
    var em=a==='Tutte'?'':areaEmoji[a]||'📍';
    var label=a==='Tutte'?'Tutte le zone':(em+' '+a);
    return '<button class="fchip-zona'+(a===S.area?' active':'')+'" data-area="'+a+'">'+label+'</button>';
  }).join('');
  document.getElementById('areaChips').innerHTML=aHtml;

  var genreEmoji={
    'Animazione':'🎨','Avventura':'🗺️','Biografico':'🎖️',
    'Commedia':'😂','Documentario':'📽️','Drammatico':'🎭',
    'Horror':'👻','Thriller':'🔪'
  };
  var gReset=S.genres.size?'<button class="genre-reset" id="gReset">&#10005; Tutti</button>':'';
  var gHtml=gReset+ALL_GENRES.map(function(g){
    var em=genreEmoji[g]||'🎬';
    return '<button class="fchip-genre'+(S.genres.has(g)?' active':'')+'" data-genre="'+g+'">'+em+' '+g+'</button>';
  }).join('');
  document.getElementById('genreChips').innerHTML=gHtml;

  document.getElementById('areaChips').querySelectorAll('.fchip-zona').forEach(function(b){
    b.addEventListener('click',function(){S.area=this.dataset.area;buildFilters();render();});
  });
  document.getElementById('genreChips').querySelectorAll('.fchip-genre').forEach(function(b){
    b.addEventListener('click',function(){
      var g=this.dataset.genre;
      S.genres.has(g)?S.genres.delete(g):S.genres.add(g);
      buildFilters();render();
    });
  });
  var gr=document.getElementById('gReset');
  if(gr) gr.addEventListener('click',function(){S.genres.clear();buildFilters();render();});
}

function buildDayStrip(){
  var wrap=document.getElementById('dayStripWrap');
  if(S.range==='today'){wrap.style.display='none';return;}
  wrap.style.display='block';
  var offs=getOffsetsForRange(S.range);
  var dayNames=['Dom','Lun','Mar','Mer','Gio','Ven','Sab'];
  var html='';
  offs.forEach(function(off){
    var d=new Date(); d.setDate(d.getDate()+off);
    var name=off===0?'Oggi':dayNames[d.getDay()];
    var num=d.getDate();
    var isActive=S.day===off;
    var todayCls=off===0?' today-dot':'';
    html+='<button class="day-btn'+(isActive?' active':'')+todayCls+'" data-off="'+off+'">'
      +'<span class="day-name">'+name+'</span>'
      +'<span class="day-num">'+num+'</span>'
      +'</button>';
  });
  document.getElementById('dayStrip').innerHTML=html;
  document.getElementById('dayStrip').querySelectorAll('.day-btn').forEach(function(b){
    b.addEventListener('click',function(){
      S.day=parseInt(this.dataset.off);
      buildDayStrip();
      render();
    });
  });
}

function setRange(r){
  S.range=r;
  S.day=getOffsetsForRange(r)[0];
  // Reset both quick chips when switching date range
  S.stasera=false;
  var sc=document.getElementById('staseraChip');
  if(sc){sc.style.background='';sc.style.color='';sc.style.borderColor='';}
  S.ov=false;
  var oc=document.getElementById('ovChip');
  if(oc){oc.style.background='';oc.style.color='';oc.style.borderColor='';}
  document.querySelectorAll('.dbt').forEach(function(b){b.classList.toggle('active',b.dataset.r===r);});
  buildDayStrip();
  render();
}

function getOffsets(){
  if(S.range==='today') return [0];
  // For week/weekend return the currently selected day
  return [S.day];
}

function getOffsetsForRange(r){
  if(r==='today'||r==='tonight') return [0];
  if(r==='weekend'){
    var res=[];
    for(var i=0;i<7;i++){var d=new Date();d.setDate(d.getDate()+i);if(d.getDay()===0||d.getDay()===6)res.push(i);}
    return res.length?res:[0];
  }
  return [0,1,2,3,4,5,6];
}

function setTab(t){
  S.tab=t;
  document.getElementById('tFilm').classList.toggle('active',t==='film');
  document.getElementById('tCinema').classList.toggle('active',t==='cinema');
  render();
}



function getFiltered(){
  var offs=getOffsets();
  var tonightOnly=S.stasera;
  return ALL_RECORDS.filter(function(r){
    if(!offs.includes(r.off)) return false;
    if(S.ov&&r.lang!=='ov') return false;
    if(tonightOnly&&!r.times.some(function(t){return parseInt(t.split(':')[0])>=19;})) return false;
    if(S.area!=='Tutte'&&r.area!==S.area) return false;
    if(S.genres.size&&!S.genres.has(r.genre)) return false;
    if(S.q){
      var q=S.q.toLowerCase();
      if(!r.film.toLowerCase().includes(q)&&!r.cinema.toLowerCase().includes(q)&&
         !r.area.toLowerCase().includes(q)&&!(r.lang==='ov'&&'originale'.includes(q))) return false;
    }
    return true;
  });
}

function render(){
  var data=getFiltered();
  var filmIndex={};
  data.forEach(function(r){
    var fk=r.filmId;
    if(!filmIndex[fk]) filmIndex[fk]={r:r,cinemas:{},langs:new Set()};
    filmIndex[fk].langs.add(r.lang);
    if(!filmIndex[fk].cinemas[r.cinemaId]) filmIndex[fk].cinemas[r.cinemaId]={cinema:r.cinema,cinemaId:r.cinemaId,area:r.area,slots:[]};
    r.times.forEach(function(t){
      var ex=filmIndex[fk].cinemas[r.cinemaId].slots.some(function(s){return s.t===t&&s.lang===r.lang&&s.off===r.off;});
      if(!ex) filmIndex[fk].cinemas[r.cinemaId].slots.push({t:t,lang:r.lang,off:r.off});
    });
  });
  var nF=Object.keys(filmIndex).length;
  var nC=new Set(data.map(function(r){return r.cinemaId;})).size;
  document.getElementById('statusText').textContent=nF+' film in '+nC+' cinema';
  var el=document.getElementById('mainContent');
  if(!nF){
    var hasFilters=S.area!=='Tutte'||S.genres.size||S.ov||S.stasera||S.q;
    el.innerHTML='<div class="empty"><div style="font-size:2rem;margin-bottom:6px">&#127916;</div>Nessuna proiezione trovata.'
      +(hasFilters?'<br><button onclick="resetAllFilters()" style="margin-top:.75rem;padding:6px 16px;border:1px solid var(--border-strong);border-radius:6px;background:var(--surface);font-family:inherit;font-size:13px;cursor:pointer;color:var(--text)">Rimuovi tutti i filtri</button>':'')
      +'</div>';
    return;
  }
  if(S.tab==='film') renderFilmGrid(filmIndex,el);
  else renderCinemaList(data,el);
}

function nowMin(){var n=new Date();return n.getHours()*60+n.getMinutes();}
function isToday(){return S.range==='today';}

function renderFilmGrid(filmIndex,el){
  var nm=nowMin(), today=isToday();

  // Collect all unique times across cinemas per film
  function getFilmTimes(obj){
    var seen={};
    var times=[];
    Object.values(obj.cinemas).forEach(function(cv){
      cv.slots.forEach(function(s){
        var key=s.t;
        if(!seen[key]){seen[key]=true;times.push(s.t);}
      });
    });
    return times.sort();
  }

  // Find next upcoming time (first time >= now, or first time overall)
  function nextTime(times){
    if(!today) return times[0]||null;
    for(var i=0;i<times.length;i++){
      var p=times[i].split(':');
      if(parseInt(p[0])*60+parseInt(p[1])>=nm) return times[i];
    }
    return null; // all past
  }

  // Sort: when stasera active sort by earliest evening time, else alphabetical
  var entries=Object.values(filmIndex);
  if(S.stasera){
    entries.sort(function(a,b){
      var ta=getFilmTimes(a).filter(function(t){return parseInt(t.split(':')[0])>=19;})[0]||'99:99';
      var tb=getFilmTimes(b).filter(function(t){return parseInt(t.split(':')[0])>=19;})[0]||'99:99';
      return ta.localeCompare(tb);
    });
  } else {
    entries.sort(function(a,b){return a.r.film.localeCompare(b.r.film);});
  }

  var html='<div class="film-grid">';
  entries.forEach(function(obj){
    var r=obj.r;
    var nC=Object.keys(obj.cinemas).length;
    var hasOV=obj.langs.has('ov');
    if(TMDB_KEY) fetchPoster(r.filmId,r.tmdbId);

    var allTimes=getFilmTimes(obj);
    var next=nextTime(allTimes);
    var totalShows=allTimes.length; // unique time slots across all cinemas

    // Show up to 4 pills: next highlighted, rest normal, clip with +N if more
    var MAX=4;
    var displayTimes=allTimes.slice(0,MAX);
    var extra=allTimes.length>MAX?allTimes.length-MAX:0;
    var timePills=displayTimes.map(function(t){
      var p=t.split(':'),tMin=parseInt(p[0])*60+parseInt(p[1]);
      var isPast=today&&tMin<nm;
      var isNext=today&&t===next;
      var cls=isPast?' past':isNext?' next':'';
      return '<span class="card-tp'+cls+'">'+t+'</span>';
    }).join('');
    if(extra) timePills+='<span class="card-tp" style="opacity:.5">+'+extra+'</span>';

    var langPill=hasOV?'<span class="lang-badge lang-ov">Versione originale</span>':'';

    html+='<div class="film-card" data-filmid="'+r.filmId+'">'
      +'<div class="card-poster" data-filmid="'+r.filmId+'">'
        +posterInnerHTML(r.filmId)+langPill
        +(nC>0?'<span class="poster-count">'+nC+' cinema</span>':'')
      +'</div>'
      +'<div class="card-body">'
        +'<div class="card-title">'+r.film+'</div>'
        +(allTimes.length?'<div class="card-times">'+timePills+'</div>':'')
        +'<div class="card-meta">'
          +'<span class="badge-genre">'+r.genre+'</span>'
          +'<span class="card-dur showtime-count">'+totalShows+' orari</span>'
        +'</div>'
      +'</div>'
    +'</div>';
  });
  html+='</div>';
  el.innerHTML=html;
  el.querySelectorAll('.film-card').forEach(function(card){
    card.addEventListener('click',function(){openModal(this.dataset.filmid,filmIndex);});
  });
}

function renderCinemaList(data,el){
  var byCinema={};
  data.forEach(function(r){
    if(!byCinema[r.cinemaId]) byCinema[r.cinemaId]={cinema:r.cinema,area:r.area,address:r.address,films:{}};
    var fk=r.filmId;
    if(!byCinema[r.cinemaId].films[fk]) byCinema[r.cinemaId].films[fk]={film:r.film,filmId:r.filmId,genre:r.genre,dur:r.dur,slots:[]};
    r.times.forEach(function(t){
      var ex=byCinema[r.cinemaId].films[fk].slots.some(function(s){return s.t===t&&s.lang===r.lang;});
      if(!ex) byCinema[r.cinemaId].films[fk].slots.push({t:t,lang:r.lang});
    });
  });
  var nm=nowMin(), today=isToday();
  var byArea={};
  Object.values(byCinema).forEach(function(obj){
    if(!byArea[obj.area]) byArea[obj.area]=[];
    byArea[obj.area].push(obj);
  });
  Object.values(byArea).forEach(function(arr){arr.sort(function(a,b){return a.cinema.localeCompare(b.cinema);});});
  var presentAreas=AREA_ORDER.filter(function(a){return byArea[a]&&byArea[a].length;});

  var legendHtml='<div class="zone-legend">'+presentAreas.map(function(a){return '<span class="legend-item">'+a+'</span>';}).join('')+'</div>';
  var html='<div class="cinema-list">';
  presentAreas.forEach(function(area){
    var cinemas=byArea[area];
    html+='<div class="zone-header"><span class="zone-name">'+area+'</span><span class="zone-count">'+cinemas.length+' cinema</span></div>';
    cinemas.forEach(function(obj){
      var nF=Object.keys(obj.films).length;
      html+='<div class="ccard"><div class="ccard-head">'
        +'<div class="ccard-info"><div class="ccard-name">'+obj.cinema+'</div><div class="ccard-addr">'+obj.address+'</div></div>'
        +'<span class="ccard-badge">'+nF+' film</span>'
        +'</div><div class="ccard-body">';
      Object.values(obj.films).sort(function(a,b){return a.film.localeCompare(b.film);}).forEach(function(fv){
        var byLang={};
        fv.slots.forEach(function(s){if(!byLang[s.lang])byLang[s.lang]=[];byLang[s.lang].push(s.t);});
        var hasOV=byLang['ov'];
        var langInd=hasOV?'<span class="lang-badge lang-ov" style="position:static;font-size:10px;padding:2px 5px">v.o.</span>':'';
        var allSorted=fv.slots.slice().sort(function(a,b){return a.t.localeCompare(b.t);});
        var pillsHtml=allSorted.map(function(s){
          var p=s.t.split(':'),tMin=parseInt(p[0])*60+parseInt(p[1]);
          var cls=today&&tMin<nm?' past':'';
          var marker=hasOV&&s.lang!=='it'?'<sup style="font-size:8px;opacity:.7">'+s.lang+'</sup>':'';
          return '<span class="tp'+cls+'">'+s.t+marker+'</span>';
        }).join('');
        html+='<div class="cf-row"><div>'
          +'<div class="cf-head" data-filmid="'+fv.filmId+'"><span class="cf-name">'+fv.film+'</span>'+langInd+'</div>'
          +'<div class="cf-sub"><span class="badge-genre">'+fv.genre+'</span><span>'+fv.dur+' min</span></div>'
          +'</div><div class="times">'+pillsHtml+'</div></div>';
      });
      html+='</div></div>';
    });
  });
  html+='</div>';
  el.innerHTML=legendHtml+html;
  el.querySelectorAll('.ccard-head').forEach(function(h){
    h.addEventListener('click',function(){this.nextElementSibling.classList.toggle('open');});
  });
  el.querySelectorAll('.cf-head').forEach(function(h){
    h.addEventListener('click',function(e){e.stopPropagation();openModalById(this.dataset.filmid);});
  });
}

function buildFilmIndexById(filmId){
  var offs=getOffsets();
  var obj={r:null,cinemas:{},langs:new Set()};
  ALL_RECORDS.filter(function(r){return r.filmId===filmId&&offs.includes(r.off);}).forEach(function(r){
    if(!obj.r) obj.r=r;
    obj.langs.add(r.lang);
    if(!obj.cinemas[r.cinemaId]) obj.cinemas[r.cinemaId]={cinema:r.cinema,cinemaId:r.cinemaId,area:r.area,slots:[]};
    r.times.forEach(function(t){
      var ex=obj.cinemas[r.cinemaId].slots.some(function(s){return s.t===t&&s.lang===r.lang&&s.off===r.off;});
      if(!ex) obj.cinemas[r.cinemaId].slots.push({t:t,lang:r.lang,off:r.off});
    });
  });
  var idx={}; idx[filmId]=obj; return idx;
}

function openModalById(filmId){openModal(filmId,buildFilmIndexById(filmId));}

function openModal(filmId,filmIndex){
  var obj=filmIndex[filmId];
  if(!obj||!obj.r) return;
  var r=obj.r, nm=nowMin(), today=isToday();
  var anyOV=obj.langs.has('ov');
  var url=filmById[r.filmId]&&filmById[r.filmId].poster?filmById[r.filmId].poster:(posterCache[r.filmId]||null);
  var miniPoster=url
    ?'<img src="'+url+'" alt="" style="width:100%;height:100%;object-fit:cover;display:block">'
    :'<span style="font-size:2rem">'+r.emoji+'</span>';

  var rows=Object.values(obj.cinemas).sort(function(a,b){return a.cinema.localeCompare(b.cinema);}).map(function(cv){
    var allTimes=cv.slots.slice().sort(function(a,b){return a.t.localeCompare(b.t);});
    var pills=allTimes.map(function(s){
      var p=s.t.split(':'),tMin=parseInt(p[0])*60+parseInt(p[1]);
      var cls=today&&tMin<nm?' past':'';
      return '<span class="tp'+cls+'">'+s.t+'</span>';
    }).join('');
    var cinObj=cinemaById[cv.cinemaId]||{};
    var hasOV=cv.slots.some(function(s){return s.lang==='ov';});
    var ovMark=hasOV?'<span style="font-size:10px;color:var(--ov-t);font-weight:500;margin-left:5px">v.o.</span>':'';
    var buyBtn=cinObj.bookingUrl
      ?'<a class="btn-buy" href="'+cinObj.bookingUrl+'" target="_blank" rel="noopener">Acquista &#8599;</a>'
      :'';
    return '<div class="modal-crow">'
      +'<div><div class="modal-cname">'+cv.cinema+ovMark+'</div><div class="modal-carea">'+cv.area+'</div></div>'
      +'<div style="display:flex;flex-direction:column;align-items:flex-end;gap:6px">'+buyBtn+'<div class="times">'+pills+'</div></div>'
      +'</div>';
  }).join('');

  document.getElementById('modalInner').innerHTML=
    '<div class="modal-head">'
      +'<div class="modal-mini-poster">'+miniPoster+'</div>'
      +'<div class="modal-head-info">'
        +'<div class="modal-title">'+r.film+'</div>'
        +'<div class="modal-badges"><span class="badge-genre">'+r.genre+'</span>'+(ratingCache[r.filmId]?'<span class="rating-badge">&#9733; '+ratingCache[r.filmId]+'</span>':'')+'</div>'
        +'<div class="modal-meta">'
          +'<div class="meta-item"><div class="mv">'+r.dur+' min</div><div class="ml">Durata</div></div>'
          +'<div class="meta-item"><div class="mv">'+r.dir+'</div><div class="ml">Regia</div></div>'
        +'</div>'
      +'</div>'
    +'</div>'
    +'<div class="modal-info">'
      +'<div class="modal-synopsis">'+r.synopsis+'</div>'
      +'<div class="modal-cast"><strong>Cast &nbsp;</strong>'+r.cast+'</div>'
      +'<div class="modal-sl">Dove vederlo'+(anyOV?' &nbsp;<span style="font-size:10.5px;font-weight:400;color:var(--ov-t);background:var(--ov-bg);padding:2px 8px;border-radius:4px;letter-spacing:0;text-transform:none">Versione originale disponibile</span>':'')+'</div>'
      +'<div class="modal-crows">'+rows+'</div>'
    +'</div>';
  document.getElementById('modalBg').classList.add('open');
}

function closeModal(){document.getElementById('modalBg').classList.remove('open');}

function quickAction(type){
  if(type==='tonight'){
    S.stasera=!S.stasera;
    var btn=document.getElementById('staseraChip');
    if(btn){btn.style.background=S.stasera?'var(--text)':'';btn.style.color=S.stasera?'#fff':'';btn.style.borderColor=S.stasera?'var(--text)':'';}
    render();
    return;
  }
  if(type==='ov'){
    S.ov=!S.ov;
    var btn=document.getElementById('ovChip');
    if(btn){btn.style.background=S.ov?'var(--text)':'';btn.style.color=S.ov?'#fff':'';btn.style.borderColor=S.ov?'var(--text)':'';}
    render();
    return;
  }
}

document.getElementById('searchInput').addEventListener('input',function(e){
  S.q=e.target.value.trim();
  document.getElementById('searchClear').style.display=S.q?'block':'none';
  render();
});
function clearSearch(){
  S.q='';
  document.getElementById('searchInput').value='';
  document.getElementById('searchClear').style.display='none';
  render();
}
function resetAllFilters(){
  S.area='Tutte'; S.genres.clear(); S.ov=false; S.stasera=false; S.q='';
  document.getElementById('searchInput').value='';
  document.getElementById('searchClear').style.display='none';
  var oc=document.getElementById('ovChip');
  if(oc){oc.style.background='';oc.style.color='';oc.style.borderColor='';}
  var sc=document.getElementById('staseraChip');
  if(sc){sc.style.background='';sc.style.color='';sc.style.borderColor='';}
  buildFilters(); render();
}

// ── Bootstrap: load data then init ──
fetch('data.json')
  .then(function(r){ return r.json(); })
  .then(function(data){
    TMDB_KEY  = data.tmdbKey || '';
    CINEMAS   = data.cinemas;
    FILMS     = data.films;
    SHOWTIMES = data.showtimes;

    CINEMAS.forEach(function(c){ cinemaById[c.id] = c; });
    FILMS.forEach(function(f){
      filmById[f.id] = f;
      f.poster = null; // will be filled by TMDB
    });
    // Build genre list from loaded films
    ALL_GENRES = Array.from(new Set(FILMS.map(function(f){return f.genre;}))).sort();

    // Map weekday numbers (0=Sun..6=Sat) to day offsets from today
    function weekdayToOffset(wd){
      var today = new Date().getDay();
      var diff = wd - today;
      if(diff < 0) diff += 7;
      return diff;
    }

    SHOWTIMES.forEach(function(s){
      var cinema = cinemaById[s.c], film = filmById[s.f];
      if(!cinema || !film) return;
      s.days.forEach(function(wd){
        var off = weekdayToOffset(wd);
        ALL_RECORDS.push({
          off: off, weekday: wd,
          cinemaId: cinema.id, cinema: cinema.name,
          area: cinema.area, address: cinema.address,
          bookingUrl: cinema.bookingUrl || '',
          filmId: film.id, film: film.title,
          genre: film.genre, dur: film.dur,
          dir: film.dir, cast: film.cast,
          synopsis: film.synopsis, emoji: film.emoji,
          tmdbId: film.tmdbId, lang: s.lang || 'it',
          times: s.t.slice()
        });
      });
    });

    // Update footer date
    var updEl = document.getElementById('updated-date');
    if(updEl && data.updated) updEl.textContent = data.updated;

    buildFilters();
    buildDayStrip();
    render();
  })
  .catch(function(err){
    console.error('Failed to load data.json:', err);
    document.getElementById('mainContent').innerHTML =
      '<div class="empty">Errore nel caricamento dei dati. Riprova.</div>';
  });
